<?php
$payment = $this->getPayment();
$helper = Mage::helper('eloom_payu');
?>

<div class="success-detail">
  <img src="<?php echo $this->getSkinUrl('eloom/payu/images/logo.png'); ?>"/>
    <p><?php echo $helper->__('Your payment was processed by PayU'); ?></p>
    
    <p>
      <?php echo $helper->__('Your payment status is') . ': ' . $helper->__('Transaction.State.' . $payment->getCcStatus()); ?>
    </p>
    
    <p>
      <?php echo $helper->__('PayU Transaction ID') . ': ' . $payment->getLastTransId(); ?>
    </p>

    <p>
      <?php echo $helper->__('PayU Order ID') . ': ' . $this->getPayUOrderId(); ?>
    </p>
    
    <?php if ($this->isBoleto()): ?>
      <p><?php echo $helper->__('PayU Bar Code') . ': ' . $this->getBilletBarCode(); ?></p>
    <?php endif; ?>

  <?php if ($this->isBoleto()): ?>
    <p><?php echo Mage::helper('checkout')->__('Print Boleto Message'); ?></p>
    <div class="buttons-set">
      <a href="<?php echo $this->getBilletLink(); ?>" target="blank" class="button" title="<?php echo Mage::helper('checkout')->__('Print Boleto'); ?>">
        <i class="fa fa-barcode" aria-hidden="true"></i>
        <?php echo $helper->__('Print Boleto'); ?>
      </a>
    </div>
  <?php endif; ?>

  <?php if($expirationDate = $this->getExpirationDate()):?>
      <p><?= $helper->__('Expiration Date') . ': ' . $expirationDate ?></p>
  <?php endif;?>
  <?php if($qrCodeEmv = $this->getQrCodeEmv()):?>
      <p><?= $helper->__('PIX') ?></p>
      <div>
        <?php if($qrCodeImageBase64 = $this->getQrCodeImageBase64()):?>
            <div class="qr-code-image-base64">
              <?="<img width='200px' src='data:image/jpeg;base64,$qrCodeImageBase64'/>"?>
            </div>
        <?php endif;?>
          <div class="qr-code-emv">
              <div><?= $qrCodeEmv ?></div>
              <div style="display: inline-block;">
                  <svg style="display: inline-block; vertical-align: middle; margin: 0 5px 0 0; width: 20px" aria-hidden="true"
                       focusable="false" data-prefix="fas" data-icon="copy" class="svg-inline--fa fa-copy fa-w-14" role="img"
                       xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                      <path fill="blue"
                            d="M320 448v40c0 13.255-10.745 24-24 24H24c-13.255 0-24-10.745-24-24V120c0-13.255 10.745-24 24-24h72v296c0 30.879 25.121 56 56 56h168zm0-344V0H152c-13.255 0-24 10.745-24 24v368c0 13.255 10.745 24 24 24h272c13.255 0 24-10.745 24-24V128H344c-13.2 0-24-10.8-24-24zm120.971-31.029L375.029 7.029A24 24 0 0 0 358.059 0H352v96h96v-6.059a24 24 0 0 0-7.029-16.97z">
                      </path>
                  </svg>
                  <a id="payu_pix_copy" style="display: inline-block; vertical-align: middle; margin: 0 5px 0 0;"><?= $helper->__('Copy PIX code') ?></a>
                  <input style="opacity: 0; user-select: none; pointer-events: none;" type="text" value="<?= $qrCodeEmv ?>" id="payu_pix_qr_code"/>
              </div>
          </div>
      </div>
	<?php endif;?>
</div>
<script>
	jQuery(document).ready(function () {
		try {
			jQuery('#payu_pix_copy').click(function () {
				var copyText = document.getElementById('payu_pix_qr_code');

				copyText.select();
				copyText.setSelectionRange(0, 99999);
				document.execCommand("copy");

				alert("<?= $helper->__('PIX code copied')?>");
			});
		} catch (e) {
			console.error(e);
		}
	});
</script>