<?php $code = $this->getMethodCode(); ?>
<ul id="payment_form_<?php echo $code ?>" class="form-list" style="display: none;">
	<?php if($inst = $this->getInstructions()):?>
      <li class="note-msg">
          <ul>
              <li><span><?php echo $inst; ?></span></li>
          </ul>
      </li>
	<?php endif;?>
</ul>

<script type="text/javascript">
//<![CDATA[
  Eloom.PayU.PaymentPix.config = {code: "<?php echo $code ?>", amount: <?php echo $this->getGrandTotal(); ?>};
  Eloom.PayU.PaymentPix.init();
//]]>
</script>