<?php
$helper = Mage::helper('eloom_payu');
?>
<table class="form-list" cellspacing="0">
  <tbody>
    <tr>
      <td class="label"><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></td>
      <td class="value"><img src="<?php echo $this->getSkinUrl('eloom/payu/images/logo.png'); ?>"/></td>
    </tr>
    <?php if ($_specificInfo = $this->getSpecificInformation()): ?>
      <?php foreach ($_specificInfo as $_label => $_value): ?>
        <tr>
          <td class="label"><?php echo $this->escapeHtml($_label) ?></td>
          <td class="value"><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n")) ?></td>
        </tr>
      <?php endforeach; ?>
    <?php endif; ?>

    <?php if($expirationDate = $this->getExpirationDate()):?>
        <tr>
            <td class="label"><?= $helper->__('Expiration Date') ?></td>
            <td class="value expiration-date"><?= $expirationDate ?></td>
        </tr>
    <?php endif;?>
    <?php if($qrCodeEmv = $this->getQrCodeEmv()):?>
        <tr>
            <td class="label"><?= $helper->__('PIX') ?></td>
            <td class="value">
					    <?php if($qrCodeImageBase64 = $this->getQrCodeImageBase64()):?>
                  <div class="qr-code-image-base64">
								    <?="<img width='200px' src='data:image/jpeg;base64,$qrCodeImageBase64'/>"?>
                  </div>
					    <?php endif;?>
                <div class="qr-code-emv">
                    <div><?= $qrCodeEmv ?></div>
                </div>
            </td>
        </tr>
    <?php endif;?>
    <tr>
        <td class="label"></td>
        <td class="value">
          <?php echo $this->getSynchronizeButton();?><?php echo $this->getLoggerButton();?>
        </td>
    </tr>
    <tr>
        <td class="value" colspan="2"><?php echo $this->getLoggerContainer();?></td>
    </tr>
  </tbody>
</table>
<?php echo $this->getChildHtml(); ?>